services:
  react-vite-sample:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-vite-sample
    volumes:
      - ..:/workspaces/react-vite-sample
      - volume_trick:/workspaces/react-vite-sample/node_modules
    working_dir: /workspaces/react-vite-sample
    ports:
      - 5173:5173
    tty: true

volumes:
  volume_trick:
